site_configs: &site_configs
  # 导航栏 Logo 位置 HTML
  navbar_brand_html: >
    <a href="/" class="navbar-brand"><b>TensorFlow</b>China</a>
  # 导航栏扩展菜单
  navbar_html: >
    <li><a href="/topics/new">发帖</a></li>
  index_html: >
    <div class="panel panel-default index-banner">
      <div class="panel-body" style="text-align: center;">
        <img src="/banner.png" style="width: 800px; max-width: 100%;">
      </div>
    </div>
    <div class="row home-icons hidden-sm hidden-xs">
      <div class="col-md-3">
        <div class="item item1">
          <div class="icon">
            <a href="/topics"><i class="fa fa-users"></i></a>
          </div>
          <div class="text">
            <a href="/topics">Tensorflow 中文社区 <i class="pull-right fa fa-arrow-right"></i></a>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="item item2">
          <div class="icon">
            <a href="/wiki"><i class="fa fa-book"></i></a>
          </div>
          <div class="text">
            <a href="/wiki">Wiki <i class="pull-right fa fa-arrow-right"></i></a>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="item item3">
          <div class="icon">
            <a href="/jobs"><i class="fa fa-th"></i></a>
          </div>
          <div class="text">
            <a href="/jobs">招聘 <i class="pull-right fa fa-arrow-right"></i></a>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="item item4">
          <div class="icon">
            <a href="/topics/popular"><i class="fa fa-star"></i></a>
          </div>
          <div class="text">
            <a href="/topics/popular">精华文章 <i class="pull-right fa fa-arrow-right"></i></a>
          </div>
        </div>
      </div>
    </div>
  wiki_index_html: >
    <div>Wiki Home page.</div>
  wiki_sidebar_html: >
    <strong>推荐内容</strong>
    <ul>
      <li><a href="/wiki/about">关于我们</a></li>
    </ul>
  footer_html: >
    <p class="copyright">
     &copy; Powered by <a href="http://gethomeland.com">Homeland</a>.
    </p>
  after_topic_html: ""
  before_topic_html: ""
  topic_index_sidebar_html: ""
  site_index_html: "下面列出了相关网站。如果你知道还有不在此列表的，请帮忙补充。"
  custom_head_html: >
    <link rel="dns-prefetch" href="//assets.your-host.com">
  node_ids_hide_in_topics_index: ""
  ban_words_on_reply: >
    mark
    收藏
    顶
    赞
    up
  tips: >
    提示1，每个提示必须有一个空行。

    提示2

  newbie_notices: >
    <p>为提高社区质量，防止新人一来就发帖提问，注册时间超过 1 天才能发帖，请在新人阶段多浏览，看看其他老用户是如何在社区里面分享与解决问题的。</p>

defaults: &defaults
  <<: *site_configs
  # Plugin module, [topic,home,wiki,site,note,team,github,editor.code,press,jobs]
  modules: 'topic,home,wiki,site,note,team,github,editor.code,press,jobs'
  # User profile module default: all [company,twitter,website,tagline,location,alipay,paypal,qq,weibo,wechat,douban,dingding,aliwangwang,facebook,instagram,dribbble,battle_tag,psn_id,steam_id]
  profile_fields: 'website,tagline,location,alipay,qq,weibo,wechat'
  app_name: "TFCHINA"
  domain: "tensorflow-china.org"
  https: true
  default_locale: 'zh-CN'
  auto_locale: false
  admin_emails: >
    eric.guocz@gmail.com
    tao.zhou2009@gmail.com
    shin.php@gmail.com
  google_analytics_key: ""
  rack_attack:
    # limit requests in a period
    limit: 300
    # (second)
    period: 180
  elasticsearch_namespace_prefix: "tfchina_"
  asset_host: "tfchina.oss-cn-shanghai.aliyuncs.com"
  upload_url: "https://tfavatar.oss-cn-shanghai.aliyuncs.com"
  upload_provider: "aliyun" # can be  file/upyun/aliyun
  upload_access_id: "" # or username
  upload_access_secret: "" # or upyun password
  upload_bucket: "tfavatar"
  upload_aliyun_internal: true
  upload_aliyun_area: "cn-shanghai"
  mailer_provider: 'smtp'
  mailer_sender: 'no-reply@ftghub.com'
  mailer_options:
    address: '127.0.0.1'
    port: 25
    enable_starttls_auto: false
  sso:
    enable: false
    enable_provider: false
    url: ''
    secret: ''
  github_token: "6ec593cb708c05a5a3fc"
  github_secret: "e89a87f83dc64db9782aa305ed55bd03eeedf42c"
  apns_pem: ""
  blacklist_ips: ""
  reject_newbie_reply_in_the_evening: false
  newbie_limit_time: 86400

development:
  <<: *defaults

test:
  <<: *defaults
  modules: 'all'
  upload_provider: "file"
  admin_emails: >
    admin@admin.com
  sso:
    enable: false
    enable_provider: false

production:
  <<: *defaults

